sudo: required
services:
  - docker

script:
  - docker build -t jlopezzarza/moviecomparer-frontend ./static
  - docker build -t jlopezzarza/moviecomparer-api .
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jlopezzarza/moviecomparer-frontend
  - docker push jlopezzarza/moviecomparer-api
