version: '3'
services:
  static:
    build:
      dockerfile: Dockerfile.dev
      context: ./static
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./static:/app
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - TMDB_KEY=${TMDB_KEY}
  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
  redis:
    image: redis
    ports:
      - "6379:6379"
  tmdbidexporter:
    build:
      dockerfile: Dockerfile.dev
      context: ./tmdbidexporter
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379