version: '3'
services:
  static:
    build:
      dockerfile: Dockerfile.dev
      context: ./static
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./static:/app
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - TMDB_KEY=${TMDB_KEY}
  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0-beta1
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
