version: '3'
services:
  static:
    build:
      dockerfile: Dockerfile.dev
      context: ./static
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./static:/app
  back:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "8080:8080"
    environment:
      - TMDB_KEY=${TMDB_KEY}
  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
