FROM golang:alpine

RUN apk update && apk add --no-cache ca-certificates
RUN update-ca-certificates

WORKDIR /app/

COPY . .

RUN GOOS=linux CGO_ENABLED=0 go build -a -o moviecomparer

CMD ["./moviecomparer"]
